modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/platypushasnohat/Sinew/issues"
license = "MIT"

[[mods]]
modId = "sinew"
version = "${file.jarVersion}"
logoFile = "sinew.png"
itemIcon = "minecraft:string"
configBackground = "minecraft:textures/block/white_wool.png"
authors = "Barl Inc"
displayName = "Sinew"
description = '''Utilites and more'''

[[dependencies.sinew]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sinew]]
modId = "forge"
mandatory = true
versionRange = "[47.1.3,)"
ordering = "AFTER"
side = "BOTH"